services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
